---
name: Games-RailRoad
version: 0.01
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: a train simulation game
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  Getopt::Euclid: 0
  Graph: 0
  POE: 0
  Readonly: 0
  Tk: 0
  Tk::ToolBar: 0
  perl: 5.010
build_requires:
  Class::Accessor::Fast: 0
  Getopt::Euclid: 0
  Graph: 0
  POE: 0
  Readonly: 0
  Test::More: 0
  Tk: 0
  Tk::ToolBar: 0
  perl: 5.010
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Games::RailRoad:
    file: lib/Games/RailRoad.pm
    version: 0.01
  Games::RailRoad::Train:
    file: lib/Games/RailRoad/Train.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
