---
name: Games-RailRoad
version: 0.01
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: a graphical debugger for Language::Befunge
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Getopt::Euclid: 0
  List::MoreUtils: 0
  POE: 0
  Readonly: 0
  Tk: 0
  Tk::ToolBar: 0
  perl: 5.008
build_requires:
  Getopt::Euclid: 0
  List::MoreUtils: 0
  POE: 0
  Readonly: 0
  Test::More: 0
  Tk: 0
  Tk::ToolBar: 0
  perl: 5.008
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
